title: "Examatics Blog"
description: "Insights on AI-native learning, micro-assessment, and system design."
baseurl: ""
url: "https://blog.examatics.ai"

theme: null
markdown: kramdown

permalink: /articles/:title/

exclude:
  - README.md

collections:
 faq:
   output: true
   permalink: /faq/:name/